# Generated by Django 4.2.2 on 2023-06-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=12)),
                ('mondir_name', models.CharField(max_length=12, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('password', models.CharField(default=None, max_length=100, null=True)),
                ('admin_id', models.IntegerField(default=0, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
