# Generated by Django 4.2.2 on 2023-08-07 05:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userregistration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillagersModel',
            fields=[
                ('villager_id', models.AutoField(primary_key=True, serialize=False)),
                ('villager_name', models.CharField(blank=True, max_length=100)),
                ('villager_mobile_number', models.CharField(blank=True, max_length=13)),
                ('villager_chada', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('villager_blood_group', models.CharField(blank=True, max_length=10)),
                ('admin_id', models.IntegerField(default=0)),
            ],
        ),
    ]
